### ISSUE TITLE
Add useful information

### ISSUE THREAD

**Issue by kevinm6** [k0dev/erlang-notes#5]
I think on line [334-335](https://github.com/k0dev/erlang-notes/blob/859c78688141cbf60ef0b779d148f3307d8cb5d4/README.md?plain=1#L334) could be useful add `~p` meaning: 
+ `~` as `%` in other programming languages (**%** is for comment in Erlang)
+ `p` as “default” value for passed arg

**Comment by k0dev** [comment]
TODO
